import { SupabaseClient } from '@supabase/supabase-js';
import { ISettlementHandler } from '../types';

export class BeautySettlementHandler implements ISettlementHandler {
    constructor(private supabase: SupabaseClient) { }

    async settle(booking: any): Promise<void> {
        console.log('[BEAUTY_SETTLEMENT] Starting settlement for booking:', booking.id);

        // 1. Idempotency Check
        const { data: existing } = await this.supabase
            .from('beauty_appointments')
            .select('id')
            .eq('booking_id', booking.id)
            .maybeSingle();

        if (existing) {
            console.log('[BEAUTY_SETTLEMENT] Idempotent: Already processed');
            return;
        }

        // 2. Extract Metadata
        const metadata = booking.metadata || {};
        const {
            serviceId,
            venueId,
            appointmentDate,
            appointmentTime,
            guestDetails,
            specialRequests,
        } = metadata;

        // Resolve User ID (use Clerk ID as text for user_id field)
        let userId = 'GUEST';
        
        if (booking.user_id && booking.user_id !== 'GUEST') {
            // booking.user_id is the internal UUID
            // Fetch Clerk ID for the user_id text field
            const { data: userData } = await this.supabase
                .from('users')
                .select('clerk_id')
                .eq('id', booking.user_id)
                .single();

            if (userData?.clerk_id) {
                userId = userData.clerk_id;
            } else {
                // Fallback to UUID as text if Clerk ID not found
                userId = booking.user_id;
            }
        }

        if (!venueId) {
            console.error('[BEAUTY_SETTLEMENT] Critical Error: Missing venue ID');
            throw new Error('Missing venue ID in metadata');
        }

        console.log('[BEAUTY_SETTLEMENT] Resolved user_id:', userId);

        // 3. Create Domain Record
        // Note: appointment_code will be auto-generated by database trigger
        const { error } = await this.supabase
            .from('beauty_appointments')
            .insert({
                booking_id: booking.id,
                user_id: userId,
                venue_id: venueId,
                service_id: serviceId || null,
                appointment_date: appointmentDate || booking.start_date,
                appointment_time: appointmentTime || '10:00:00',
                duration_minutes: metadata.duration || 60,
                guest_name: guestDetails?.name || booking.guest_details?.name || 'Guest',
                guest_email: guestDetails?.email || booking.guest_email || booking.guest_details?.email || 'no-email@example.com',
                guest_phone: guestDetails?.phone || booking.guest_details?.phone || null,
                special_requests: specialRequests || null,
                status: 'confirmed',
                confirmed_at: new Date().toISOString(),
                metadata: {
                    booking_source: 'checkout',
                    total_amount: Number(booking.total_amount),
                    currency: booking.currency || 'USD',
                    payment_status: booking.payment_status === 'paid' ? 'paid' : 'pending',
                },
            });

        if (error) {
            console.error('[BEAUTY_SETTLEMENT] Creation failed', error);
            throw error;
        }

        console.log('[BEAUTY_SETTLEMENT] Successfully created beauty_appointments record');
    }
}
