-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  location text,
  description text,
  rating numeric DEFAULT 0,
  reviews_count integer DEFAULT 0,
  price numeric NOT NULL,
  old_price numeric,
  image_url text,
  images ARRAY,
  is_instant boolean DEFAULT false,
  features jsonb DEFAULT '{}'::jsonb,
  ticket_types jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category text,
  highlights ARRAY DEFAULT '{}'::text[],
  inclusions ARRAY DEFAULT '{}'::text[],
  exclusions ARRAY DEFAULT '{}'::text[],
  important_info text,
  CONSTRAINT activities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  label character varying,
  full_name character varying NOT NULL,
  phone character varying,
  country character varying NOT NULL,
  city character varying NOT NULL,
  district character varying,
  line1 character varying NOT NULL,
  line2 character varying,
  postal_code character varying,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.beauty_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid UNIQUE,
  user_id text NOT NULL,
  venue_id uuid NOT NULL,
  service_id uuid,
  appointment_code text UNIQUE,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  guest_name text NOT NULL,
  guest_phone text,
  guest_email text,
  special_requests text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])),
  confirmed_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beauty_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT beauty_appointments_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.beauty_venues(id),
  CONSTRAINT beauty_appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.beauty_services(id)
);
CREATE TABLE public.beauty_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  service_id uuid,
  user_id text NOT NULL,
  booking_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  service_rating integer CHECK (service_rating IS NULL OR service_rating >= 1 AND service_rating <= 5),
  cleanliness_rating integer CHECK (cleanliness_rating IS NULL OR cleanliness_rating >= 1 AND cleanliness_rating <= 5),
  value_rating integer CHECK (value_rating IS NULL OR value_rating >= 1 AND value_rating <= 5),
  photos ARRAY,
  visit_date date,
  is_verified boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  helpful_count integer DEFAULT 0 CHECK (helpful_count >= 0),
  response_text text,
  response_date timestamp with time zone,
  status text DEFAULT 'approved'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beauty_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT beauty_reviews_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.beauty_venues(id),
  CONSTRAINT beauty_reviews_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.beauty_services(id)
);
CREATE TABLE public.beauty_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  duration_minutes integer DEFAULT 60 CHECK (duration_minutes > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  currency text DEFAULT 'USD'::text,
  image_url text,
  badge text,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beauty_services_pkey PRIMARY KEY (id),
  CONSTRAINT beauty_services_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.beauty_venues(id)
);
CREATE TABLE public.beauty_venues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  address text,
  city text,
  district text,
  ward text,
  latitude numeric,
  longitude numeric,
  location_summary text,
  phone text,
  email text,
  website text,
  categories ARRAY,
  price_range text CHECK (price_range = ANY (ARRAY['budget'::text, 'moderate'::text, 'premium'::text, 'luxury'::text])),
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  review_count integer DEFAULT 0 CHECK (review_count >= 0),
  cover_image_url text,
  images ARRAY,
  operating_hours jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  owner_user_id text,
  amenities ARRAY,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beauty_venues_pkey PRIMARY KEY (id)
);
CREATE TABLE public.booking_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  promotion_type character varying CHECK (promotion_type::text = ANY (ARRAY['voucher'::character varying, 'coupon'::character varying, 'tcent'::character varying]::text[])),
  reference_id character varying,
  amount_applied numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  rule_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_discounts_pkey PRIMARY KEY (id),
  CONSTRAINT booking_discounts_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  event_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_events_pkey PRIMARY KEY (id),
  CONSTRAINT booking_events_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  external_user_ref text,
  type text NOT NULL,
  channel text NOT NULL,
  recipient text NOT NULL,
  status text DEFAULT 'PENDING'::text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  subject text,
  body text,
  template_id text,
  template_data jsonb,
  provider text,
  external_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  booking_id uuid NOT NULL,
  user_uuid uuid,
  CONSTRAINT booking_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT booking_notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_notifications_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id)
);
CREATE TABLE public.booking_reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  reservation_ref character varying,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['held'::character varying, 'confirmed'::character varying, 'released'::character varying, 'expired'::character varying]::text[])),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT booking_reservations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL CHECK (category = ANY (ARRAY['hotel'::text, 'flight'::text, 'restaurant'::text, 'activity'::text, 'event'::text, 'wellness'::text, 'beauty'::text, 'transport'::text, 'shop'::text, 'entertainment'::text])),
  title text NOT NULL,
  description text,
  image_url text,
  location_summary text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  status text DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['held'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text, 'payment_failed'::text, 'refunded'::text, 'pending'::text])),
  total_amount numeric NOT NULL,
  currency text DEFAULT 'VND'::text,
  booking_code text UNIQUE,
  guest_details jsonb,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id text,
  payment_status character varying DEFAULT 'unpaid'::character varying CHECK (payment_status::text = ANY (ARRAY['unpaid'::character varying, 'pending'::character varying, 'paid'::character varying, 'refunded'::character varying, 'failed'::character varying]::text[])),
  idempotency_key character varying UNIQUE,
  breakdown jsonb,
  expires_at timestamp with time zone,
  held_at timestamp with time zone DEFAULT now(),
  guest_email text,
  CONSTRAINT bookings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  logo_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  cover_url character varying,
  tagline character varying,
  description text,
  follower_count integer DEFAULT 0,
  rating_avg numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  response_rate integer DEFAULT 100,
  response_time character varying DEFAULT 'within 1 hour'::character varying,
  on_time_ship_rate integer DEFAULT 100,
  joined_date date DEFAULT CURRENT_DATE,
  product_count integer DEFAULT 0,
  CONSTRAINT brands_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cart_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  qty integer NOT NULL CHECK (qty > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  currency character varying DEFAULT 'USD'::character varying,
  title_snapshot character varying,
  variant_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id),
  CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id character varying,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  currency character varying DEFAULT 'USD'::character varying,
  shipping_method_id uuid,
  shipping_address_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT carts_pkey PRIMARY KEY (id),
  CONSTRAINT carts_shipping_method_id_fkey FOREIGN KEY (shipping_method_id) REFERENCES public.shipping_methods(id),
  CONSTRAINT carts_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_id uuid,
  slug character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  image_url character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text, 'function'::text])),
  content text,
  function_call jsonb,
  function_result jsonb,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.coupon_usages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coupon_id uuid NOT NULL,
  user_id uuid,
  order_id uuid NOT NULL,
  discount_applied integer NOT NULL CHECK (discount_applied > 0),
  currency character varying DEFAULT 'USD'::character varying,
  used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupon_usages_pkey PRIMARY KEY (id),
  CONSTRAINT coupon_usages_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT coupon_usages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT coupon_usages_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.shop_orders(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  title character varying,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['percent'::character varying, 'fixed'::character varying]::text[])),
  discount_value integer NOT NULL CHECK (discount_value > 0),
  min_order_subtotal integer DEFAULT 0 CHECK (min_order_subtotal >= 0),
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  usage_limit_total integer CHECK (usage_limit_total IS NULL OR usage_limit_total > 0),
  usage_limit_per_user integer DEFAULT 1 CHECK (usage_limit_per_user > 0),
  current_usage_count integer DEFAULT 0 CHECK (current_usage_count >= 0),
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'disabled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dining_appointment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid UNIQUE,
  user_id text NOT NULL,
  venue_id uuid NOT NULL,
  table_id uuid,
  appointment_code text UNIQUE,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 120,
  guest_count integer NOT NULL CHECK (guest_count >= 1),
  guest_name text NOT NULL,
  guest_phone text,
  guest_email text,
  special_requests text,
  occasion text,
  dietary_restrictions ARRAY,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'seated'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])),
  confirmed_at timestamp with time zone,
  confirmed_by text,
  seated_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  deposit_amount numeric DEFAULT 0,
  deposit_paid boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_appointment_pkey PRIMARY KEY (id),
  CONSTRAINT dining_appointment_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id),
  CONSTRAINT dining_appointment_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.dining_tables(id)
);
CREATE TABLE public.dining_blocked_dates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text,
  start_time time without time zone,
  end_time time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_blocked_dates_pkey PRIMARY KEY (id),
  CONSTRAINT dining_blocked_dates_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.dining_cart (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  venue_name character varying,
  venue_image text,
  reservation_date date NOT NULL,
  reservation_time time without time zone NOT NULL,
  guest_count integer NOT NULL CHECK (guest_count > 0),
  special_requests text,
  occasion character varying,
  dietary_restrictions ARRAY,
  table_id uuid,
  duration_minutes integer DEFAULT 120,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_cart_pkey PRIMARY KEY (id),
  CONSTRAINT dining_cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT dining_cart_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id),
  CONSTRAINT dining_cart_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.dining_tables(id)
);
CREATE TABLE public.dining_menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  menu_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  original_price numeric,
  currency text DEFAULT 'VND'::text,
  category text,
  dietary_tags ARRAY,
  allergens ARRAY,
  image_url text,
  is_available boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  is_popular boolean DEFAULT false,
  display_order integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT dining_menu_items_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES public.dining_menus(id),
  CONSTRAINT dining_menu_items_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.dining_menus (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_menus_pkey PRIMARY KEY (id),
  CONSTRAINT dining_menus_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.dining_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reservation_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  food_rating integer CHECK (food_rating >= 1 AND food_rating <= 5),
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  ambiance_rating integer CHECK (ambiance_rating >= 1 AND ambiance_rating <= 5),
  value_rating integer CHECK (value_rating >= 1 AND value_rating <= 5),
  title character varying,
  comment text,
  photos ARRAY,
  visit_date date,
  is_verified boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  response_text text,
  response_date timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT dining_reviews_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id),
  CONSTRAINT dining_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.dining_tables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  table_number text NOT NULL,
  name text,
  min_capacity integer DEFAULT 1 CHECK (min_capacity >= 1),
  max_capacity integer NOT NULL CHECK (max_capacity >= 1),
  section text,
  floor integer DEFAULT 1,
  features ARRAY,
  is_active boolean DEFAULT true,
  is_reservable boolean DEFAULT true,
  premium_charge numeric DEFAULT 0 CHECK (premium_charge >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_tables_pkey PRIMARY KEY (id),
  CONSTRAINT dining_tables_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.dining_time_slots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venue_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  slot_duration_minutes integer DEFAULT 30,
  max_reservations_per_slot integer DEFAULT 5,
  max_guests_per_slot integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_time_slots_pkey PRIMARY KEY (id),
  CONSTRAINT dining_time_slots_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.dining_venues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  address text,
  city text,
  district text,
  ward text,
  latitude numeric,
  longitude numeric,
  location_summary text,
  phone text,
  email text,
  website text,
  cuisine_type ARRAY,
  price_range text CHECK (price_range = ANY (ARRAY['budget'::text, 'moderate'::text, 'upscale'::text, 'fine_dining'::text])),
  capacity integer DEFAULT 0 CHECK (capacity >= 0),
  operating_hours jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  review_count integer DEFAULT 0 CHECK (review_count >= 0),
  cover_image_url text,
  images ARRAY,
  owner_user_id text,
  amenities ARRAY,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_venues_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dining_wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dining_wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT dining_wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT dining_wishlist_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.dining_venues(id)
);
CREATE TABLE public.entertainment_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_reference text NOT NULL UNIQUE,
  user_id text NOT NULL,
  item_id uuid NOT NULL,
  session_id uuid,
  organizer_id uuid,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text,
  total_quantity integer NOT NULL,
  total_amount numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  payment_status text DEFAULT 'pending'::text,
  payment_method text,
  payment_reference text,
  payment_date timestamp with time zone,
  booking_status text DEFAULT 'confirmed'::text,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  refund_amount numeric,
  refund_date timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  booking_id uuid UNIQUE,
  external_user_ref text,
  user_uuid uuid,
  confirmation_code text UNIQUE,
  CONSTRAINT entertainment_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_bookings_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_bookings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.entertainment_sessions(id),
  CONSTRAINT entertainment_bookings_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.entertainment_organizers(id),
  CONSTRAINT entertainment_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT entertainment_bookings_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id)
);
CREATE TABLE public.entertainment_cart (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT entertainment_cart_pkey PRIMARY KEY (id)
);
CREATE TABLE public.entertainment_cart_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cart_id uuid NOT NULL,
  item_id uuid NOT NULL,
  session_id uuid,
  ticket_type_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric DEFAULT ((quantity)::numeric * unit_price),
  currency character varying DEFAULT 'USD'::character varying,
  reserved_until timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_cart_items_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES public.entertainment_ticket_types(id),
  CONSTRAINT entertainment_cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.entertainment_cart(id),
  CONSTRAINT entertainment_cart_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_cart_items_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.entertainment_sessions(id)
);
CREATE TABLE public.entertainment_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  parent_id uuid,
  icon_url text,
  banner_url text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_categories_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.entertainment_categories(id)
);
CREATE TABLE public.entertainment_followers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  organizer_id uuid NOT NULL,
  notify_new_events boolean DEFAULT true,
  notify_updates boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_followers_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_followers_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.entertainment_organizers(id)
);
CREATE TABLE public.entertainment_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  subtitle text,
  description text,
  type text NOT NULL,
  slug text NOT NULL UNIQUE,
  category_id uuid,
  organizer_id uuid,
  min_price numeric,
  max_price numeric,
  currency character varying DEFAULT 'USD'::character varying,
  status text DEFAULT 'draft'::text,
  is_featured boolean DEFAULT false,
  is_trending boolean DEFAULT false,
  available boolean DEFAULT true,
  location jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  video_url text,
  base_capacity integer DEFAULT 0,
  total_bookings integer DEFAULT 0,
  total_views integer DEFAULT 0,
  total_wishlist integer DEFAULT 0,
  rating_average numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  urgency_threshold integer DEFAULT 20,
  low_stock_threshold integer DEFAULT 10,
  metadata jsonb DEFAULT '{}'::jsonb,
  seo_title text,
  seo_description text,
  seo_keywords ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  CONSTRAINT entertainment_items_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.entertainment_categories(id),
  CONSTRAINT entertainment_items_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.entertainment_organizers(id)
);
CREATE TABLE public.entertainment_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  item_id uuid,
  booking_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  sent_via jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_notifications_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.entertainment_bookings(id)
);
CREATE TABLE public.entertainment_organizers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  cover_image_url text,
  email text,
  phone text,
  website text,
  social_links jsonb DEFAULT '{}'::jsonb,
  rating_average numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  follower_count integer DEFAULT 0,
  event_count integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_organizers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.entertainment_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  booking_id uuid,
  user_id text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  images jsonb DEFAULT '[]'::jsonb,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  is_flagged boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_reviews_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.entertainment_bookings(id)
);
CREATE TABLE public.entertainment_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  session_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration_minutes integer,
  capacity integer NOT NULL,
  booked_count integer DEFAULT 0,
  available_count integer DEFAULT (capacity - booked_count),
  price_override numeric,
  status text DEFAULT 'available'::text,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_sessions_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id)
);
CREATE TABLE public.entertainment_ticket_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  price numeric NOT NULL,
  original_price numeric,
  currency character varying DEFAULT 'USD'::character varying,
  max_quantity_per_order integer DEFAULT 10,
  total_available integer,
  total_sold integer DEFAULT 0,
  benefits jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  held_count integer DEFAULT 0,
  CONSTRAINT entertainment_ticket_types_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_ticket_types_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id)
);
CREATE TABLE public.entertainment_tickets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_number text NOT NULL UNIQUE,
  booking_id uuid NOT NULL,
  ticket_type_id uuid,
  attendee_name text,
  attendee_email text,
  seat_number text,
  qr_code_url text,
  qr_code_data text NOT NULL,
  is_redeemed boolean DEFAULT false,
  redeemed_at timestamp with time zone,
  redeemed_by text,
  status text DEFAULT 'valid'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_tickets_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.entertainment_bookings(id),
  CONSTRAINT entertainment_tickets_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES public.entertainment_ticket_types(id)
);
CREATE TABLE public.entertainment_trending_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL UNIQUE,
  trending_score numeric NOT NULL,
  views_24h integer DEFAULT 0,
  bookings_24h integer DEFAULT 0,
  wishlist_24h integer DEFAULT 0,
  revenue_24h numeric DEFAULT 0,
  trending_rank integer,
  category_rank integer,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  CONSTRAINT entertainment_trending_cache_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_trending_cache_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id)
);
CREATE TABLE public.entertainment_urgency_signals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid,
  session_id uuid,
  signal_type text NOT NULL,
  remaining_quantity integer,
  percentage_sold numeric,
  time_until_event interval,
  badge_text text NOT NULL,
  badge_color text DEFAULT 'orange'::text,
  priority integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT entertainment_urgency_signals_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_urgency_signals_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_urgency_signals_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.entertainment_sessions(id)
);
CREATE TABLE public.entertainment_waitlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  session_id uuid,
  user_id text NOT NULL,
  email text NOT NULL,
  phone text,
  status text DEFAULT 'waiting'::text,
  notified_at timestamp with time zone,
  position integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '48:00:00'::interval),
  CONSTRAINT entertainment_waitlist_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_waitlist_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id),
  CONSTRAINT entertainment_waitlist_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.entertainment_sessions(id)
);
CREATE TABLE public.entertainment_wishlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  item_id uuid NOT NULL,
  notify_on_discount boolean DEFAULT false,
  notify_on_availability boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entertainment_wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_wishlist_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.entertainment_items(id)
);
CREATE TABLE public.event_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid UNIQUE,
  user_uuid uuid,
  external_user_ref text,
  event_id uuid NOT NULL,
  session_id uuid NOT NULL,
  ticket_type_id uuid NOT NULL,
  confirmation_code text NOT NULL UNIQUE,
  adult_count integer DEFAULT 0 CHECK (adult_count >= 0),
  child_count integer DEFAULT 0 CHECK (child_count >= 0),
  total_tickets integer DEFAULT (adult_count + child_count),
  unit_price numeric NOT NULL,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'VND'::text,
  discount_amount numeric DEFAULT 0,
  tcent_used integer DEFAULT 0,
  tcent_earned integer DEFAULT 0,
  guest_name text NOT NULL,
  guest_email text NOT NULL,
  guest_phone text,
  attendees jsonb DEFAULT '[]'::jsonb,
  special_requests text,
  qr_codes jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'checked_in'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text, 'no_show'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'partially_refunded'::text, 'failed'::text])),
  confirmed_at timestamp with time zone,
  checked_in_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  refund_amount numeric,
  refunded_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  booking_source text DEFAULT 'web'::text,
  user_agent text,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT event_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT event_bookings_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id),
  CONSTRAINT event_bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_bookings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.event_sessions(id),
  CONSTRAINT event_bookings_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES public.event_ticket_types(id)
);
CREATE TABLE public.event_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  session_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone,
  timezone text DEFAULT 'Asia/Ho_Chi_Minh'::text,
  name text,
  description text,
  doors_open_time time without time zone,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'on_sale'::text, 'sold_out'::text, 'cancelled'::text, 'completed'::text])),
  total_capacity integer,
  venue_override text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT event_sessions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.event_ticket_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  session_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  original_price numeric,
  currency text DEFAULT 'VND'::text,
  total_capacity integer NOT NULL CHECK (total_capacity >= 0),
  sold_count integer DEFAULT 0 CHECK (sold_count >= 0),
  held_count integer DEFAULT 0 CHECK (held_count >= 0),
  min_per_order integer DEFAULT 1 CHECK (min_per_order >= 1),
  max_per_order integer DEFAULT 10 CHECK (max_per_order >= 1),
  perks ARRAY DEFAULT '{}'::text[],
  sale_start_at timestamp with time zone,
  sale_end_at timestamp with time zone,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  badge text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_ticket_types_pkey PRIMARY KEY (id),
  CONSTRAINT event_ticket_types_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_ticket_types_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.event_sessions(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text UNIQUE,
  description text,
  short_description text,
  venue_name text,
  address text,
  city text,
  district text,
  latitude numeric,
  longitude numeric,
  location_summary text,
  category text CHECK (category = ANY (ARRAY['concert'::text, 'festival'::text, 'sports'::text, 'theater'::text, 'exhibition'::text, 'conference'::text, 'workshop'::text, 'other'::text])),
  tags ARRAY DEFAULT '{}'::text[],
  cover_image_url text,
  images ARRAY DEFAULT '{}'::text[],
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  review_count integer DEFAULT 0 CHECK (review_count >= 0),
  organizer_name text,
  organizer_logo_url text,
  organizer_contact text,
  highlights ARRAY DEFAULT '{}'::text[],
  inclusions ARRAY DEFAULT '{}'::text[],
  exclusions ARRAY DEFAULT '{}'::text[],
  terms_and_conditions text,
  important_info text,
  age_restriction text,
  dress_code text,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  meta_title text,
  meta_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fare_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  offer_id uuid,
  cancellation_allowed boolean DEFAULT true,
  cancellation_window_hours integer,
  cancellation_fee_percent numeric,
  cancellation_fee_fixed numeric,
  no_show_fee numeric,
  changes_allowed boolean DEFAULT true,
  change_window_hours integer,
  change_fee_percent numeric,
  change_fee_fixed numeric,
  same_day_change_fee numeric,
  advance_purchase_days integer,
  minimum_stay_nights integer,
  maximum_stay_nights integer,
  saturday_night_stay_required boolean DEFAULT false,
  reissue_fee numeric,
  upgrade_fee numeric,
  downgrade_refund_percent numeric,
  checked_baggage_count integer DEFAULT 0,
  checked_baggage_weight text,
  carryon_baggage_count integer DEFAULT 1,
  excess_baggage_fee_per_kg numeric,
  seat_selection_allowed boolean DEFAULT true,
  seat_selection_fee numeric DEFAULT 0,
  advance_seat_selection boolean DEFAULT false,
  meal_included boolean DEFAULT false,
  lounge_access boolean DEFAULT false,
  priority_boarding boolean DEFAULT false,
  fast_track_security boolean DEFAULT false,
  rules_text text,
  rules_html text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fare_rules_pkey PRIMARY KEY (id),
  CONSTRAINT fare_rules_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.flight_offers(id)
);
CREATE TABLE public.flight_booking_modifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  flight_booking_id uuid,
  user_id text NOT NULL,
  type text NOT NULL,
  field_name text,
  old_value jsonb,
  new_value jsonb,
  fee_charged numeric DEFAULT 0,
  requires_approval boolean DEFAULT false,
  approval_status text,
  approved_by text,
  approved_at timestamp with time zone,
  rejection_reason text,
  modified_by text NOT NULL,
  modification_source text DEFAULT 'USER'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flight_booking_modifications_pkey PRIMARY KEY (id),
  CONSTRAINT booking_modifications_booking_id_fkey FOREIGN KEY (flight_booking_id) REFERENCES public.flight_bookings(id)
);
CREATE TABLE public.flight_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  external_user_ref text,
  offer_id uuid,
  flight_id uuid,
  search_session_id uuid,
  pnr text NOT NULL UNIQUE,
  booking_reference text,
  supplier_id uuid,
  passengers jsonb NOT NULL CHECK (jsonb_array_length(passengers) > 0),
  passenger_count integer DEFAULT jsonb_array_length(passengers),
  lead_passenger_email text NOT NULL,
  lead_passenger_phone text NOT NULL,
  contact_info jsonb NOT NULL,
  billing_address jsonb,
  base_fare numeric NOT NULL,
  taxes_fees numeric NOT NULL,
  total_baggage_fees numeric DEFAULT 0,
  total_seat_fees numeric DEFAULT 0,
  total_meal_fees numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  tcent_used integer DEFAULT 0,
  tcent_earned integer DEFAULT 0,
  discount_code text,
  discount_amount numeric DEFAULT 0,
  promo_applied jsonb,
  status text DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'CONFIRMED'::text, 'TICKETED'::text, 'CANCELLED'::text, 'COMPLETED'::text, 'REFUNDED'::text, 'FAILED'::text])),
  booking_type text DEFAULT 'CONFIRMED'::text,
  hold_until timestamp with time zone,
  hold_payment_deadline timestamp with time zone,
  is_hold_booking boolean DEFAULT false,
  payment_status text DEFAULT 'PENDING'::text,
  payment_id text,
  payment_method text,
  payment_completed_at timestamp with time zone,
  ticketing_status text DEFAULT 'PENDING'::text,
  ticketing_deadline timestamp with time zone,
  tickets jsonb DEFAULT '[]'::jsonb,
  seat_assignments jsonb DEFAULT '{}'::jsonb,
  baggage_allowance jsonb DEFAULT '{}'::jsonb,
  meal_selections jsonb DEFAULT '{}'::jsonb,
  special_requests text,
  fare_rules_accepted boolean DEFAULT false,
  fare_rules_accepted_at timestamp with time zone,
  fare_rules_version integer,
  terms_accepted boolean DEFAULT false,
  terms_accepted_at timestamp with time zone,
  is_modified boolean DEFAULT false,
  original_booking_id uuid,
  modification_fee numeric DEFAULT 0,
  cancelled_by text,
  cancellation_reason text,
  refund_amount numeric,
  refund_status text,
  refund_processed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  agent_id text,
  booking_source text DEFAULT 'WEB'::text,
  booked_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  ticketed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_id uuid UNIQUE,
  user_uuid uuid,
  CONSTRAINT flight_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT flight_bookings_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.flight_offers(id),
  CONSTRAINT flight_bookings_flight_id_fkey FOREIGN KEY (flight_id) REFERENCES public.flights(id),
  CONSTRAINT flight_bookings_search_session_id_fkey FOREIGN KEY (search_session_id) REFERENCES public.flight_search_sessions(id),
  CONSTRAINT flight_bookings_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.flight_suppliers(id),
  CONSTRAINT flight_bookings_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id),
  CONSTRAINT flight_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.flight_checkins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  flight_booking_id uuid,
  passenger_index integer NOT NULL,
  checked_in_at timestamp with time zone DEFAULT now(),
  boarding_pass_number text,
  boarding_group text,
  boarding_position integer,
  gate text,
  seat_assigned text,
  status text DEFAULT 'CHECKED_IN'::text,
  boarded_at timestamp with time zone,
  boarding_pass_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flight_checkins_pkey PRIMARY KEY (id),
  CONSTRAINT booking_checkins_booking_id_fkey FOREIGN KEY (flight_booking_id) REFERENCES public.flight_bookings(id)
);
CREATE TABLE public.flight_offers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  offer_key text NOT NULL UNIQUE,
  flight_id uuid,
  supplier_id uuid,
  supplier_offer_id text,
  total_price numeric NOT NULL CHECK (total_price >= 0::numeric),
  base_fare numeric NOT NULL,
  taxes_fees numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  seats_available integer NOT NULL DEFAULT 0 CHECK (seats_available >= 0),
  last_seat_available boolean DEFAULT false,
  cabin_class text DEFAULT 'ECONOMY'::text,
  fare_family text DEFAULT 'STANDARD'::text,
  fare_basis_code text,
  booking_class text,
  refundable boolean DEFAULT false,
  changeable boolean DEFAULT false,
  change_fee numeric DEFAULT 0,
  cancellation_fee numeric DEFAULT 0,
  baggage_included jsonb DEFAULT '{}'::jsonb,
  baggage_fee numeric DEFAULT 0,
  fare_rules_id uuid,
  advance_purchase_required integer,
  minimum_stay integer,
  maximum_stay integer,
  blackout_dates jsonb DEFAULT '[]'::jsonb,
  provider text DEFAULT 'internal'::text,
  valid_until timestamp with time zone,
  popularity_score integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flight_offers_pkey PRIMARY KEY (id),
  CONSTRAINT flight_offers_flight_id_fkey FOREIGN KEY (flight_id) REFERENCES public.flights(id),
  CONSTRAINT flight_offers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.flight_suppliers(id)
);
CREATE TABLE public.flight_search_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  search_key text NOT NULL UNIQUE,
  origin text NOT NULL,
  destination text NOT NULL,
  departure_date date NOT NULL,
  search_params jsonb DEFAULT '{}'::jsonb,
  results jsonb NOT NULL,
  result_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT flight_search_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flight_search_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text,
  origin text NOT NULL,
  destination text NOT NULL,
  departure_date date NOT NULL,
  return_date date,
  passenger_adults integer DEFAULT 1,
  passenger_children integer DEFAULT 0,
  passenger_infants integer DEFAULT 0,
  cabin_class text DEFAULT 'ECONOMY'::text,
  trip_type text DEFAULT 'ONE_WAY'::text,
  filters jsonb DEFAULT '{}'::jsonb,
  searched_at timestamp with time zone DEFAULT now(),
  results_count integer DEFAULT 0,
  selected_offer_id uuid,
  converted boolean DEFAULT false,
  ip_address inet,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT flight_search_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flight_suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  api_endpoint text,
  api_key_encrypted text,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  response_time_avg_ms integer,
  success_rate numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flight_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flight_tickets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  flight_booking_id uuid,
  ticket_number text NOT NULL UNIQUE,
  passenger_index integer NOT NULL,
  passenger_name text NOT NULL,
  flight_id uuid,
  fare_basis_code text,
  booking_class text,
  status text DEFAULT 'ISSUED'::text,
  issued_at timestamp with time zone DEFAULT now(),
  issued_by text,
  eticket_url text,
  eticket_pdf_path text,
  is_valid boolean DEFAULT true,
  void_reason text,
  voided_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flight_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT booking_tickets_booking_id_fkey FOREIGN KEY (flight_booking_id) REFERENCES public.flight_bookings(id),
  CONSTRAINT booking_tickets_flight_id_fkey FOREIGN KEY (flight_id) REFERENCES public.flights(id)
);
CREATE TABLE public.flights (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  airline_code text NOT NULL,
  airline_name text,
  flight_number text NOT NULL,
  origin text NOT NULL,
  origin_name text,
  destination text NOT NULL,
  destination_name text,
  departure_at timestamp with time zone NOT NULL,
  arrival_at timestamp with time zone NOT NULL,
  duration_minutes integer,
  aircraft text,
  seat_classes jsonb DEFAULT '[]'::jsonb,
  amenities jsonb DEFAULT '[]'::jsonb,
  baggage_allowance jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  currency text DEFAULT 'USD'::text,
  status text DEFAULT 'scheduled'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flights_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_booking_modifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid,
  user_id text NOT NULL,
  modification_type text NOT NULL,
  old_values jsonb NOT NULL,
  new_values jsonb NOT NULL,
  price_difference_cents integer DEFAULT 0,
  refund_amount_cents integer DEFAULT 0,
  additional_charge_cents integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'completed'::text])),
  processed_at timestamp with time zone,
  processed_by text,
  reason text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_booking_modifications_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_booking_modifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.hotel_bookings(id)
);
CREATE TABLE public.hotel_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  external_user_ref text,
  hotel_id uuid,
  room_id uuid,
  partner_id uuid,
  confirmation_code text NOT NULL UNIQUE,
  partner_booking_ref text,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  nights_count smallint DEFAULT (check_out_date - check_in_date),
  guest_name text NOT NULL,
  guest_email text NOT NULL,
  guest_phone text NOT NULL,
  guest_count jsonb NOT NULL,
  special_requests text,
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  nightly_rate_cents integer NOT NULL,
  tax_cents integer DEFAULT 0,
  fees_cents integer DEFAULT 0,
  discount_cents integer DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  commission_cents integer DEFAULT 0,
  commission_rate numeric,
  tcent_used integer DEFAULT 0,
  tcent_earned integer DEFAULT 0,
  tcent_earn_rate numeric DEFAULT 0.05,
  working_pass_applied boolean DEFAULT false,
  working_pass_discount_cents integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'checked_in'::text, 'checked_out'::text, 'cancelled'::text, 'no_show'::text, 'modified'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'partially_refunded'::text, 'failed'::text])),
  payment_id text,
  is_modified boolean DEFAULT false,
  original_booking_id uuid,
  modification_count integer DEFAULT 0,
  modified_at timestamp with time zone,
  cancellation_policy text,
  cancelled_at timestamp with time zone,
  cancelled_by text,
  cancellation_reason text,
  cancellation_fee_cents integer,
  refund_amount_cents integer,
  refund_status text,
  refunded_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  booking_source text DEFAULT 'web'::text,
  user_agent text,
  ip_address inet,
  booked_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_id uuid UNIQUE,
  user_uuid uuid,
  CONSTRAINT hotel_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT hotel_bookings_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id),
  CONSTRAINT hotel_bookings_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotels(id),
  CONSTRAINT hotel_bookings_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.hotel_rooms(id),
  CONSTRAINT hotel_bookings_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.hotel_partners(id),
  CONSTRAINT hotel_bookings_original_booking_id_fkey FOREIGN KEY (original_booking_id) REFERENCES public.hotel_bookings(id)
);
CREATE TABLE public.hotel_partner_listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hotel_id uuid,
  partner_id uuid,
  partner_hotel_id text NOT NULL,
  partner_hotel_url text,
  is_active boolean DEFAULT true,
  last_synced_at timestamp with time zone,
  sync_status text DEFAULT 'active'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_partner_listings_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_partner_listings_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotels(id),
  CONSTRAINT hotel_partner_listings_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.hotel_partners(id)
);
CREATE TABLE public.hotel_partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  logo_url text,
  website_url text,
  commission_rate numeric DEFAULT 0.10,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  contact jsonb DEFAULT '{}'::jsonb,
  api_config jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_id uuid,
  partner_id uuid,
  date date NOT NULL,
  price_cents integer NOT NULL CHECK (price_cents >= 0),
  currency text NOT NULL DEFAULT 'USD'::text,
  available_rooms smallint DEFAULT 0 CHECK (available_rooms >= 0),
  min_nights smallint DEFAULT 1,
  max_nights smallint,
  cancellation_policy text DEFAULT 'flexible'::text,
  refundable boolean DEFAULT true,
  breakfast_included boolean DEFAULT false,
  rate_plan text DEFAULT 'standard'::text,
  original_price_cents integer,
  discount_percentage numeric,
  is_best_price boolean DEFAULT false,
  price_match_guarantee boolean DEFAULT false,
  tcent_earn_rate numeric DEFAULT 0.05,
  tcent_eligible boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_rates_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_rates_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.hotel_rooms(id),
  CONSTRAINT hotel_rates_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.hotel_partners(id)
);
CREATE TABLE public.hotel_rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hotel_id uuid,
  code text NOT NULL,
  title text NOT NULL,
  description text,
  capacity smallint DEFAULT 1 CHECK (capacity > 0),
  bed_type text,
  bed_count smallint DEFAULT 1,
  size_sqm numeric,
  floor_range text,
  view_type text,
  images jsonb DEFAULT '[]'::jsonb,
  amenities jsonb DEFAULT '[]'::jsonb,
  is_smoking boolean DEFAULT false,
  is_accessible boolean DEFAULT false,
  max_adults smallint DEFAULT 2,
  max_children smallint DEFAULT 1,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'maintenance'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_rooms_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotels(id)
);
CREATE TABLE public.hotels (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  address jsonb DEFAULT '{}'::jsonb,
  star_rating smallint CHECK (star_rating >= 0 AND star_rating <= 5),
  images jsonb DEFAULT '[]'::jsonb,
  amenities jsonb DEFAULT '[]'::jsonb,
  policies jsonb DEFAULT '{}'::jsonb,
  contact jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'pending'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  best_price integer,
  CONSTRAINT hotels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mail_service (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  category text NOT NULL,
  recipient_email text NOT NULL,
  subject text NOT NULL,
  body_html text NOT NULL,
  status text DEFAULT 'pending'::text,
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mail_service_pkey PRIMARY KEY (id),
  CONSTRAINT mail_service_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['reward'::character varying, 'booking'::character varying, 'system'::character varying]::text[])),
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  deep_link text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  title_snapshot character varying NOT NULL,
  sku_snapshot character varying,
  variant_snapshot jsonb,
  image_url_snapshot character varying,
  qty integer NOT NULL CHECK (qty > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  line_total numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.shop_orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id),
  CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.order_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  old_status character varying,
  new_status character varying NOT NULL,
  old_payment_status character varying,
  new_payment_status character varying,
  changed_by_type character varying DEFAULT 'system'::character varying,
  changed_by_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.shop_orders(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  provider character varying NOT NULL,
  provider_transaction_id character varying,
  idempotency_key character varying UNIQUE,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'success'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  amount numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  webhook_payload jsonb,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.price_alerts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  external_user_ref text,
  origin text NOT NULL,
  destination text NOT NULL,
  departure_date date,
  target_price numeric,
  current_lowest_price numeric,
  is_active boolean DEFAULT true,
  last_checked_at timestamp with time zone,
  notification_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  user_uuid uuid NOT NULL,
  CONSTRAINT price_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT price_alerts_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  url character varying NOT NULL,
  alt character varying,
  sort_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  sku character varying NOT NULL UNIQUE,
  title character varying,
  price real NOT NULL CHECK (price >= 0::double precision),
  compare_at_price integer,
  currency character varying DEFAULT 'USD'::character varying,
  stock_on_hand integer NOT NULL DEFAULT 0 CHECK (stock_on_hand >= 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id)
);
CREATE TABLE public.quest_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quest_id uuid NOT NULL,
  user_id uuid NOT NULL,
  submission_data jsonb NOT NULL,
  status character varying NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quest_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT quest_submissions_quest_id_fkey FOREIGN KEY (quest_id) REFERENCES public.quests(id),
  CONSTRAINT quest_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.quests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text NOT NULL,
  quest_type character varying NOT NULL,
  reward_amount integer NOT NULL,
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  user_id text NOT NULL,
  category text NOT NULL,
  item_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.saved_travelers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone_number text,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  nationality text,
  passport_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saved_travelers_pkey PRIMARY KEY (id),
  CONSTRAINT saved_travelers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.shipping_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  base_fee integer NOT NULL DEFAULT 0,
  currency character varying DEFAULT 'USD'::character varying,
  estimated_days_min integer,
  estimated_days_max integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shop_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  brand_id uuid NOT NULL,
  last_message_content text,
  last_message_at timestamp with time zone DEFAULT now(),
  unread_count_user integer DEFAULT 0,
  unread_count_brand integer DEFAULT 0,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT shop_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT shop_conversations_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.shop_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  content text,
  image_urls ARRAY,
  product_id uuid,
  order_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  sender_user_id uuid,
  sender_brand_id uuid,
  CONSTRAINT shop_messages_pkey PRIMARY KEY (id),
  CONSTRAINT shop_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.users(id),
  CONSTRAINT shop_messages_sender_brand_id_fkey FOREIGN KEY (sender_brand_id) REFERENCES public.brands(id),
  CONSTRAINT shop_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.shop_conversations(id),
  CONSTRAINT shop_messages_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id),
  CONSTRAINT shop_messages_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.shop_orders(id)
);
CREATE TABLE public.shop_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  user_id uuid,
  cart_id uuid,
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  discount_total numeric DEFAULT 0 CHECK (discount_total >= 0::numeric),
  shipping_total numeric DEFAULT 0 CHECK (shipping_total >= 0::numeric),
  tcent_earned integer DEFAULT 0 CHECK (tcent_earned >= 0),
  tcent_used integer DEFAULT 0 CHECK (tcent_used >= 0),
  shipping_method_id uuid,
  shipping_address_snapshot jsonb NOT NULL,
  tracking_numbers jsonb,
  customer_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_id uuid,
  CONSTRAINT shop_orders_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT shop_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT shop_orders_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id),
  CONSTRAINT shop_orders_shipping_method_id_fkey FOREIGN KEY (shipping_method_id) REFERENCES public.shipping_methods(id)
);
CREATE TABLE public.shop_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  brand_id uuid,
  slug character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  product_type character varying NOT NULL DEFAULT 'physical'::character varying,
  status character varying NOT NULL DEFAULT 'draft'::character varying,
  rating_avg numeric DEFAULT 0,
  review_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_products_pkey PRIMARY KEY (id),
  CONSTRAINT shop_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT shop_products_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.shop_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  body text,
  photos ARRAY,
  is_verified_purchase boolean DEFAULT false,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT shop_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id),
  CONSTRAINT shop_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT shop_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.shop_orders(id)
);
CREATE TABLE public.shop_wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT shop_wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT shop_wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.shop_products(id)
);
CREATE TABLE public.spin_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  reward_type character varying NOT NULL CHECK (reward_type::text = ANY (ARRAY['TCENT'::character varying, 'VOUCHER'::character varying, 'NONE'::character varying]::text[])),
  reward_value text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT spin_history_pkey PRIMARY KEY (id),
  CONSTRAINT spin_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tcent_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  transaction_type character varying NOT NULL,
  status character varying NOT NULL,
  balance_after integer,
  reference_type character varying,
  reference_id uuid,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  total_spend_usd numeric,
  CONSTRAINT tcent_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT tcent_ledger_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tier_configs (
  tier_name character varying NOT NULL,
  earning_multiplier numeric DEFAULT 1.00,
  min_lifetime_spend_usd numeric NOT NULL,
  min_total_orders integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tier_configs_pkey PRIMARY KEY (tier_name)
);
CREATE TABLE public.transport_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  route_id uuid,
  passenger_info jsonb,
  vehicle_snapshot jsonb,
  status text DEFAULT 'confirmed'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transport_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT transport_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT transport_bookings_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transport_routes(id)
);
CREATE TABLE public.transport_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text,
  rating numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transport_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transport_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  type text,
  vehicle_type text,
  origin text NOT NULL,
  destination text NOT NULL,
  departure_time timestamp with time zone NOT NULL,
  arrival_time timestamp with time zone NOT NULL,
  price numeric NOT NULL,
  seats_available integer DEFAULT 0,
  vehicle_details jsonb,
  images ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  booking_id uuid,
  CONSTRAINT transport_routes_pkey PRIMARY KEY (id),
  CONSTRAINT transport_routes_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.transport_providers(id),
  CONSTRAINT transport_routes_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.user_flight_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL UNIQUE,
  preferred_cabin text DEFAULT 'ECONOMY'::text,
  preferred_airlines jsonb DEFAULT '[]'::jsonb,
  excluded_airlines jsonb DEFAULT '[]'::jsonb,
  max_stops integer DEFAULT 2,
  preferred_departure_time text,
  preferred_arrival_time text,
  seat_preference text,
  meal_preference text,
  frequent_flyer_programs jsonb DEFAULT '[]'::jsonb,
  price_alert_enabled boolean DEFAULT false,
  price_alert_threshold_percent numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_flight_preferences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_search_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_user_ref text,
  category text NOT NULL CHECK (category = ANY (ARRAY['flight'::text, 'hotel'::text, 'vouchers'::text, 'events'::text, 'dining'::text, 'activities'::text, 'wellness'::text, 'beauty'::text, 'entertainment'::text, 'shop'::text, 'transport'::text])),
  search_params jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT user_search_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_search_history_user_uuid_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_streaks (
  user_id uuid NOT NULL,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  last_claim_at timestamp with time zone,
  daily_actions_completed jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT user_streaks_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_streaks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  voucher_id uuid NOT NULL,
  status character varying NOT NULL,
  acquired_at timestamp with time zone DEFAULT now(),
  used_at timestamp with time zone,
  CONSTRAINT user_vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT user_vouchers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_vouchers_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id text NOT NULL UNIQUE,
  email text NOT NULL,
  first_name text,
  last_name text,
  name text,
  image_url text,
  membership_tier text NOT NULL DEFAULT 'BRONZE'::text CHECK (membership_tier = ANY (ARRAY['BRONZE'::text, 'SILVER'::text, 'GOLD'::text, 'PLATINUM'::text])),
  tcent_balance integer NOT NULL DEFAULT 0 CHECK (tcent_balance >= 0),
  tcent_pending integer NOT NULL DEFAULT 0 CHECK (tcent_pending >= 0),
  lifetime_spend numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  language text DEFAULT 'en'::text,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  is_email_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  bio text,
  city text,
  country text,
  phone_number text,
  total_orders_completed integer DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.variant_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  variant_id uuid NOT NULL,
  option_name character varying NOT NULL,
  option_value character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT variant_options_pkey PRIMARY KEY (id),
  CONSTRAINT variant_options_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.voucher_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  tcent_cost integer NOT NULL CHECK (tcent_cost >= 0),
  discount_mode character varying NOT NULL CHECK (discount_mode::text = ANY (ARRAY['percent'::character varying, 'fixed'::character varying, 'shipping'::character varying]::text[])),
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  currency character varying DEFAULT 'USD'::character varying,
  min_spend_threshold integer DEFAULT 0 CHECK (min_spend_threshold >= 0),
  total_inventory integer CHECK (total_inventory IS NULL OR total_inventory > 0),
  redeemed_count integer DEFAULT 0 CHECK (redeemed_count >= 0),
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  validity_days integer DEFAULT 30 CHECK (validity_days > 0),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT voucher_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  voucher_type character varying NOT NULL,
  discount_value numeric NOT NULL,
  min_spend numeric DEFAULT 0,
  total_usage_limit integer,
  current_usage_count integer DEFAULT 0,
  is_purchasable boolean DEFAULT false,
  tcent_price integer,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vouchers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wellness (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  location text,
  rating numeric DEFAULT 0,
  reviews_count integer DEFAULT 0,
  price numeric NOT NULL,
  image_url text,
  images ARRAY,
  badge text,
  duration text,
  description text,
  features jsonb DEFAULT '[]'::jsonb,
  reviews_data jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wellness_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_user_ref text,
  item_type text NOT NULL,
  item_id text NOT NULL,
  title text NOT NULL,
  image_url text,
  price numeric,
  created_at timestamp with time zone DEFAULT now(),
  user_uuid uuid,
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(id)
);